version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
environment:
  matrix:
  - MSVC: ON
  - CLANG: ON
  - PYTHON: C:\Python36-x64
install:
- cmd: >-
    git submodule update --init --recursive


    set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip"

    appveyor DownloadFile %NINJA_URL% -FileName ninja.zip

    7z x ninja.zip -oC:\opt\ninja > nul

    set PATH=C:\opt\ninja;%PATH%

    ninja --version


    set SWIG_URL="http://prdownloads.sourceforge.net/swig/swigwin-3.0.12.zip"

    appveyor DownloadFile %SWIG_URL% -FileName swig.zip

    7z x swig.zip -oC:\opt

    move C:\opt\swigwin-* C:\opt\swig

    set PATH=C:\opt\swig;%PATH%

    swig -version


    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
build_script:
- cmd: call av_build.cmd
